apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

components:
  - github.com/ocm-sop/api-domain-tls-cert?ref=main

resources:
  - patch-api-server.yaml